spring:
  datasource:
    hikari:
      username: root
      password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&amp;characterEncoding=utf8;allowMultiQueries=true&&useSSL=true
  resources:
    static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  profiles:
    active: dev
  # mongodb配置
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
  # mybatis配置
mybatis:
    mapper-locations: classpath*:mappers/**/*.xml
    #config-location: classpath:mybatis-config.xml
    type-aliases-package: com.jason.entity
logging:
  config: classpath:log4j2.xml
    
    
    
    